-- ============================================================
-- WEBSITE BUILDER MODULE — Complete Database Migration Script
-- Execute this script in Neon PostgreSQL
-- All tables prefixed with WB_
-- Includes DROP TABLE IF EXISTS for fresh re-runs
-- ============================================================

-- ══════════════════════════════════════════════════════════════
-- DROP EXISTING TABLES (reverse dependency order)
-- ══════════════════════════════════════════════════════════════

DROP TABLE IF EXISTS "WB_ActivityLog" CASCADE;
DROP TABLE IF EXISTS "WB_FormSubmissions" CASCADE;
DROP TABLE IF EXISTS "WB_GlobalBlockUsages" CASCADE;
DROP TABLE IF EXISTS "WB_PageVersions" CASCADE;
DROP TABLE IF EXISTS "WB_Media" CASCADE;
DROP TABLE IF EXISTS "WB_Pages" CASCADE;
DROP TABLE IF EXISTS "WB_GlobalBlocks" CASCADE;
DROP TABLE IF EXISTS "WB_BrandProfiles" CASCADE;
DROP TABLE IF EXISTS "WB_Templates" CASCADE;
DROP TABLE IF EXISTS "WB_Sites" CASCADE;

-- ══════════════════════════════════════════════════════════════
-- 1. WB_Sites — Core site entity
-- ══════════════════════════════════════════════════════════════

CREATE TABLE "WB_Sites" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" varchar(200) NOT NULL,
    "Slug" varchar(100) NOT NULL,
    "Description" text,
    "Favicon" varchar(2000),
    "ThemeJson" jsonb NOT NULL DEFAULT '{}',
    "Published" boolean NOT NULL DEFAULT false,
    "PublishedAt" timestamp with time zone,
    "PublishedUrl" varchar(500),
    "DefaultLanguage" varchar(10) DEFAULT 'en',
    "LanguagesJson" jsonb,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" varchar(100) NOT NULL DEFAULT 'system',
    "ModifiedBy" varchar(100),
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" varchar(100),
    CONSTRAINT "UQ_WB_Sites_Slug" UNIQUE ("Slug")
);

-- Note: Slug index is already created by the UNIQUE constraint above
CREATE INDEX "IX_WB_Sites_Published" ON "WB_Sites" ("Published");
CREATE INDEX "IX_WB_Sites_IsDeleted" ON "WB_Sites" ("IsDeleted");
CREATE INDEX "IX_WB_Sites_CreatedAt" ON "WB_Sites" ("CreatedAt" DESC);
CREATE INDEX "IX_WB_Sites_Name" ON "WB_Sites" ("Name");

-- ══════════════════════════════════════════════════════════════
-- 2. WB_Pages — Pages belong to sites
-- ══════════════════════════════════════════════════════════════

CREATE TABLE "WB_Pages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SiteId" integer NOT NULL,
    "Title" varchar(200) NOT NULL,
    "Slug" varchar(100) NOT NULL DEFAULT '',
    "ComponentsJson" jsonb NOT NULL DEFAULT '[]',
    "SeoJson" jsonb NOT NULL DEFAULT '{}',
    "TranslationsJson" jsonb,
    "IsHomePage" boolean NOT NULL DEFAULT false,
    "SortOrder" integer NOT NULL DEFAULT 0,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" varchar(100) NOT NULL DEFAULT 'system',
    "ModifiedBy" varchar(100),
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" varchar(100),
    CONSTRAINT "FK_WB_Pages_Sites" FOREIGN KEY ("SiteId") 
        REFERENCES "WB_Sites" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_WB_Pages_SiteId" ON "WB_Pages" ("SiteId");
CREATE INDEX "IX_WB_Pages_Slug" ON "WB_Pages" ("SiteId", "Slug");
CREATE INDEX "IX_WB_Pages_SortOrder" ON "WB_Pages" ("SiteId", "SortOrder");
CREATE INDEX "IX_WB_Pages_IsDeleted" ON "WB_Pages" ("IsDeleted");
CREATE INDEX "IX_WB_Pages_IsHomePage" ON "WB_Pages" ("SiteId", "IsHomePage");

-- ══════════════════════════════════════════════════════════════
-- 3. WB_PageVersions — Component history snapshots
-- ══════════════════════════════════════════════════════════════

CREATE TABLE "WB_PageVersions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PageId" integer NOT NULL,
    "SiteId" integer NOT NULL,
    "VersionNumber" integer NOT NULL DEFAULT 1,
    "ComponentsJson" jsonb NOT NULL DEFAULT '[]',
    "ChangeMessage" varchar(500),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "CreatedBy" varchar(100) NOT NULL DEFAULT 'system',
    CONSTRAINT "FK_WB_PageVersions_Pages" FOREIGN KEY ("PageId") 
        REFERENCES "WB_Pages" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_WB_PageVersions_Sites" FOREIGN KEY ("SiteId") 
        REFERENCES "WB_Sites" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_WB_PageVersions_PageId" ON "WB_PageVersions" ("PageId");
CREATE INDEX "IX_WB_PageVersions_SiteId" ON "WB_PageVersions" ("SiteId");
CREATE INDEX "IX_WB_PageVersions_Version" ON "WB_PageVersions" ("PageId", "VersionNumber" DESC);
CREATE INDEX "IX_WB_PageVersions_CreatedAt" ON "WB_PageVersions" ("CreatedAt" DESC);

-- ══════════════════════════════════════════════════════════════
-- 4. WB_GlobalBlocks — Reusable components across sites
-- ══════════════════════════════════════════════════════════════

CREATE TABLE "WB_GlobalBlocks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" varchar(200) NOT NULL,
    "Description" text,
    "ComponentJson" jsonb NOT NULL DEFAULT '{}',
    "Category" varchar(100),
    "Tags" text,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" varchar(100) NOT NULL DEFAULT 'system',
    "ModifiedBy" varchar(100),
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" varchar(100)
);

CREATE INDEX "IX_WB_GlobalBlocks_Name" ON "WB_GlobalBlocks" ("Name");
CREATE INDEX "IX_WB_GlobalBlocks_Category" ON "WB_GlobalBlocks" ("Category");
CREATE INDEX "IX_WB_GlobalBlocks_IsDeleted" ON "WB_GlobalBlocks" ("IsDeleted");

-- ══════════════════════════════════════════════════════════════
-- 5. WB_GlobalBlockUsages — Tracks where global blocks are used
-- ══════════════════════════════════════════════════════════════

CREATE TABLE "WB_GlobalBlockUsages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "GlobalBlockId" integer NOT NULL,
    "SiteId" integer NOT NULL,
    "PageId" integer,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_WB_GlobalBlockUsages_Blocks" FOREIGN KEY ("GlobalBlockId") 
        REFERENCES "WB_GlobalBlocks" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_WB_GlobalBlockUsages_Sites" FOREIGN KEY ("SiteId") 
        REFERENCES "WB_Sites" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_WB_GlobalBlockUsages_Pages" FOREIGN KEY ("PageId") 
        REFERENCES "WB_Pages" ("Id") ON DELETE SET NULL
);

CREATE INDEX "IX_WB_GlobalBlockUsages_BlockId" ON "WB_GlobalBlockUsages" ("GlobalBlockId");
CREATE INDEX "IX_WB_GlobalBlockUsages_SiteId" ON "WB_GlobalBlockUsages" ("SiteId");

-- ══════════════════════════════════════════════════════════════
-- 6. WB_BrandProfiles — Reusable theme presets
-- ══════════════════════════════════════════════════════════════

CREATE TABLE "WB_BrandProfiles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" varchar(200) NOT NULL,
    "Description" text,
    "ThemeJson" jsonb NOT NULL DEFAULT '{}',
    "IsBuiltIn" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" varchar(100) NOT NULL DEFAULT 'system',
    "ModifiedBy" varchar(100),
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" varchar(100)
);

CREATE INDEX "IX_WB_BrandProfiles_Name" ON "WB_BrandProfiles" ("Name");
CREATE INDEX "IX_WB_BrandProfiles_IsBuiltIn" ON "WB_BrandProfiles" ("IsBuiltIn");
CREATE INDEX "IX_WB_BrandProfiles_IsDeleted" ON "WB_BrandProfiles" ("IsDeleted");

-- ══════════════════════════════════════════════════════════════
-- 7. WB_FormSubmissions — Visitor form submissions
-- ══════════════════════════════════════════════════════════════

CREATE TABLE "WB_FormSubmissions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SiteId" integer NOT NULL,
    "PageId" integer,
    "FormComponentId" varchar(100) NOT NULL,
    "FormLabel" varchar(200) NOT NULL DEFAULT '',
    "PageTitle" varchar(200) NOT NULL DEFAULT '',
    "DataJson" jsonb NOT NULL DEFAULT '{}',
    "Source" varchar(50) DEFAULT 'website',
    "WebhookStatus" varchar(20),
    "WebhookResponse" text,
    "SubmittedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "IpAddress" varchar(45),
    CONSTRAINT "FK_WB_FormSubmissions_Sites" FOREIGN KEY ("SiteId") 
        REFERENCES "WB_Sites" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_WB_FormSubmissions_Pages" FOREIGN KEY ("PageId") 
        REFERENCES "WB_Pages" ("Id") ON DELETE SET NULL
);

CREATE INDEX "IX_WB_FormSubmissions_SiteId" ON "WB_FormSubmissions" ("SiteId");
CREATE INDEX "IX_WB_FormSubmissions_PageId" ON "WB_FormSubmissions" ("PageId");
CREATE INDEX "IX_WB_FormSubmissions_FormComponentId" ON "WB_FormSubmissions" ("FormComponentId");
CREATE INDEX "IX_WB_FormSubmissions_SubmittedAt" ON "WB_FormSubmissions" ("SubmittedAt" DESC);

-- ══════════════════════════════════════════════════════════════
-- 8. WB_Media — Uploaded images/files (URLs only, no binary)
-- ══════════════════════════════════════════════════════════════

CREATE TABLE "WB_Media" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SiteId" integer,
    "FileName" varchar(255) NOT NULL,
    "OriginalName" varchar(500) NOT NULL,
    "FilePath" varchar(1000) NOT NULL,
    "FileUrl" varchar(2000) NOT NULL,
    "FileSize" bigint NOT NULL DEFAULT 0,
    "ContentType" varchar(100) NOT NULL DEFAULT 'image/jpeg',
    "Width" integer,
    "Height" integer,
    "Folder" varchar(200),
    "AltText" varchar(500),
    "UploadedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UploadedBy" varchar(100) NOT NULL DEFAULT 'system',
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "FK_WB_Media_Sites" FOREIGN KEY ("SiteId") 
        REFERENCES "WB_Sites" ("Id") ON DELETE SET NULL
);

CREATE INDEX "IX_WB_Media_SiteId" ON "WB_Media" ("SiteId");
CREATE INDEX "IX_WB_Media_Folder" ON "WB_Media" ("Folder");
CREATE INDEX "IX_WB_Media_ContentType" ON "WB_Media" ("ContentType");
CREATE INDEX "IX_WB_Media_IsDeleted" ON "WB_Media" ("IsDeleted");
CREATE INDEX "IX_WB_Media_UploadedAt" ON "WB_Media" ("UploadedAt" DESC);

-- ══════════════════════════════════════════════════════════════
-- 9. WB_Templates — Custom + built-in site templates
-- ══════════════════════════════════════════════════════════════

CREATE TABLE "WB_Templates" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" varchar(200) NOT NULL,
    "Description" text,
    "Category" varchar(100) NOT NULL DEFAULT 'general',
    "PreviewImageUrl" varchar(2000),
    "ThemeJson" jsonb NOT NULL DEFAULT '{}',
    "PagesJson" jsonb NOT NULL DEFAULT '[]',
    "Tags" text,
    "IsPremium" boolean NOT NULL DEFAULT false,
    "IsBuiltIn" boolean NOT NULL DEFAULT false,
    "SortOrder" integer NOT NULL DEFAULT 0,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" varchar(100) NOT NULL DEFAULT 'system',
    "ModifiedBy" varchar(100),
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" varchar(100)
);

CREATE INDEX "IX_WB_Templates_Category" ON "WB_Templates" ("Category");
CREATE INDEX "IX_WB_Templates_IsBuiltIn" ON "WB_Templates" ("IsBuiltIn");
CREATE INDEX "IX_WB_Templates_IsPremium" ON "WB_Templates" ("IsPremium");
CREATE INDEX "IX_WB_Templates_IsDeleted" ON "WB_Templates" ("IsDeleted");
CREATE INDEX "IX_WB_Templates_SortOrder" ON "WB_Templates" ("SortOrder");

-- ══════════════════════════════════════════════════════════════
-- 10. WB_ActivityLog — Audit trail for all mutations
-- ══════════════════════════════════════════════════════════════

CREATE TABLE "WB_ActivityLog" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SiteId" integer NOT NULL,
    "PageId" integer,
    "Action" varchar(50) NOT NULL,
    "EntityType" varchar(50) NOT NULL,
    "Details" text,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "CreatedBy" varchar(100) NOT NULL DEFAULT 'system',
    CONSTRAINT "FK_WB_ActivityLog_Sites" FOREIGN KEY ("SiteId") 
        REFERENCES "WB_Sites" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_WB_ActivityLog_SiteId" ON "WB_ActivityLog" ("SiteId");
CREATE INDEX "IX_WB_ActivityLog_Action" ON "WB_ActivityLog" ("Action");
CREATE INDEX "IX_WB_ActivityLog_EntityType" ON "WB_ActivityLog" ("EntityType");
CREATE INDEX "IX_WB_ActivityLog_CreatedAt" ON "WB_ActivityLog" ("CreatedAt" DESC);
CREATE INDEX "IX_WB_ActivityLog_CreatedBy" ON "WB_ActivityLog" ("CreatedBy");

-- ══════════════════════════════════════════════════════════════
-- SEED DATA — Built-in Brand Profiles (7 themes)
-- ══════════════════════════════════════════════════════════════

INSERT INTO "WB_BrandProfiles" ("Name", "Description", "ThemeJson", "IsBuiltIn", "CreatedBy")
VALUES
('Default Blue', 'Clean and professional blue theme', 
 '{"primaryColor":"#3b82f6","secondaryColor":"#64748b","accentColor":"#f59e0b","backgroundColor":"#ffffff","textColor":"#1e293b","headingFont":"Inter, sans-serif","bodyFont":"Inter, sans-serif","borderRadius":8,"spacing":16,"shadowStyle":"subtle","buttonStyle":"rounded","sectionPadding":1,"fontScale":1,"letterSpacing":0,"linkStyle":"hover-underline","headingTransform":"none"}', 
 true, 'system'),

('Dark Mode', 'Elegant dark theme with purple accents',
 '{"primaryColor":"#8b5cf6","secondaryColor":"#94a3b8","accentColor":"#f59e0b","backgroundColor":"#0f172a","textColor":"#f1f5f9","headingFont":"Inter, sans-serif","bodyFont":"Inter, sans-serif","borderRadius":8,"spacing":16,"shadowStyle":"subtle","buttonStyle":"rounded","sectionPadding":1,"fontScale":1,"letterSpacing":0,"linkStyle":"hover-underline","headingTransform":"none"}', 
 true, 'system'),

('Coral Sunset', 'Warm and inviting with coral tones',
 '{"primaryColor":"#ef4444","secondaryColor":"#6b7280","accentColor":"#f97316","backgroundColor":"#ffffff","textColor":"#1e293b","headingFont":"Georgia, serif","bodyFont":"Inter, sans-serif","borderRadius":8,"spacing":16,"shadowStyle":"subtle","buttonStyle":"rounded","sectionPadding":1,"fontScale":1,"letterSpacing":0,"linkStyle":"hover-underline","headingTransform":"none"}', 
 true, 'system'),

('Forest Green', 'Natural and earthy green palette',
 '{"primaryColor":"#059669","secondaryColor":"#4b5563","accentColor":"#d97706","backgroundColor":"#fafaf9","textColor":"#1e293b","headingFont":"Inter, sans-serif","bodyFont":"Inter, sans-serif","borderRadius":8,"spacing":16,"shadowStyle":"subtle","buttonStyle":"rounded","sectionPadding":1,"fontScale":1,"letterSpacing":0,"linkStyle":"hover-underline","headingTransform":"none"}', 
 true, 'system'),

('Corporate Navy', 'Serious business tone with navy and teal',
 '{"primaryColor":"#1e40af","secondaryColor":"#475569","accentColor":"#0891b2","backgroundColor":"#ffffff","textColor":"#1e293b","headingFont":"Georgia, serif","bodyFont":"Inter, sans-serif","borderRadius":4,"spacing":16,"shadowStyle":"subtle","buttonStyle":"rounded","sectionPadding":1,"fontScale":1,"letterSpacing":0,"linkStyle":"hover-underline","headingTransform":"none"}', 
 true, 'system'),

('Playful Pink', 'Fun and creative pink and purple',
 '{"primaryColor":"#ec4899","secondaryColor":"#6b7280","accentColor":"#8b5cf6","backgroundColor":"#ffffff","textColor":"#1e293b","headingFont":"Inter, sans-serif","bodyFont":"Inter, sans-serif","borderRadius":16,"spacing":16,"shadowStyle":"subtle","buttonStyle":"rounded","sectionPadding":1,"fontScale":1,"letterSpacing":0,"linkStyle":"hover-underline","headingTransform":"none"}', 
 true, 'system'),

('Automotive Red', 'Bold auto repair and car shop theme',
 '{"primaryColor":"#dc2626","secondaryColor":"#1e293b","accentColor":"#f59e0b","backgroundColor":"#ffffff","textColor":"#0f172a","headingFont":"Space Grotesk, sans-serif","bodyFont":"Inter, sans-serif","borderRadius":8,"spacing":16,"shadowStyle":"subtle","buttonStyle":"rounded","sectionPadding":1,"fontScale":1,"letterSpacing":0,"linkStyle":"hover-underline","headingTransform":"none"}', 
 true, 'system');

-- ══════════════════════════════════════════════════════════════
-- SEED DATA — Built-in Templates (8 starter templates)
-- ══════════════════════════════════════════════════════════════

-- 1. Blank Canvas
INSERT INTO "WB_Templates" ("Name", "Description", "Category", "ThemeJson", "PagesJson", "Tags", "IsBuiltIn", "SortOrder", "CreatedBy")
VALUES (
  'Blank Canvas',
  'Start from scratch with a clean slate. Perfect for custom designs.',
  'starter',
  '{"primaryColor":"#3b82f6","secondaryColor":"#64748b","accentColor":"#f59e0b","backgroundColor":"#ffffff","textColor":"#1e293b","headingFont":"Inter, sans-serif","bodyFont":"Inter, sans-serif","borderRadius":8,"spacing":16,"shadowStyle":"subtle","buttonStyle":"rounded","sectionPadding":1,"fontScale":1}',
  '[{"title":"Home","slug":"","isHomePage":true,"sortOrder":0,"componentsJson":"[]","seoJson":"{\"title\":\"Home\"}"}]',
  'blank,starter,empty',
  true, 0, 'system'
);

-- 2. Business Landing Page
INSERT INTO "WB_Templates" ("Name", "Description", "Category", "ThemeJson", "PagesJson", "Tags", "IsBuiltIn", "SortOrder", "CreatedBy")
VALUES (
  'Business Landing Page',
  'Professional landing page with hero, features, testimonials and CTA sections.',
  'business',
  '{"primaryColor":"#1e40af","secondaryColor":"#475569","accentColor":"#0891b2","backgroundColor":"#ffffff","textColor":"#1e293b","headingFont":"Inter, sans-serif","bodyFont":"Inter, sans-serif","borderRadius":8,"spacing":16,"shadowStyle":"subtle","buttonStyle":"rounded","sectionPadding":1,"fontScale":1}',
  '[{"title":"Home","slug":"","isHomePage":true,"sortOrder":0,"componentsJson":"[{\"id\":\"hero-1\",\"type\":\"hero\",\"label\":\"Hero Section\",\"props\":{\"title\":\"Grow Your Business Online\",\"subtitle\":\"The all-in-one platform to build, launch, and scale your digital presence.\",\"ctaText\":\"Get Started\",\"ctaLink\":\"#contact\",\"alignment\":\"center\",\"backgroundType\":\"gradient\"}},{\"id\":\"features-1\",\"type\":\"features\",\"label\":\"Features\",\"props\":{\"title\":\"Why Choose Us\",\"subtitle\":\"Everything you need to succeed online\",\"columns\":3,\"items\":[{\"icon\":\"Zap\",\"title\":\"Lightning Fast\",\"description\":\"Optimized for speed and performance\"},{\"icon\":\"Shield\",\"title\":\"Secure\",\"description\":\"Enterprise-grade security built in\"},{\"icon\":\"BarChart\",\"title\":\"Analytics\",\"description\":\"Track your growth with detailed insights\"}]}},{\"id\":\"cta-1\",\"type\":\"cta-banner\",\"label\":\"Call to Action\",\"props\":{\"title\":\"Ready to get started?\",\"subtitle\":\"Join thousands of satisfied customers today.\",\"ctaText\":\"Start Free Trial\",\"ctaLink\":\"#signup\"}}]","seoJson":"{\"title\":\"Business Landing Page\",\"description\":\"Professional business website\"}"},{"title":"About","slug":"about","isHomePage":false,"sortOrder":1,"componentsJson":"[{\"id\":\"hero-about\",\"type\":\"hero\",\"label\":\"About Hero\",\"props\":{\"title\":\"About Us\",\"subtitle\":\"Our story and mission\",\"alignment\":\"center\"}}]","seoJson":"{\"title\":\"About Us\"}"},{"title":"Contact","slug":"contact","isHomePage":false,"sortOrder":2,"componentsJson":"[{\"id\":\"form-contact\",\"type\":\"form\",\"label\":\"Contact Form\",\"props\":{\"title\":\"Get in Touch\",\"fields\":[{\"name\":\"name\",\"label\":\"Name\",\"type\":\"text\",\"required\":true},{\"name\":\"email\",\"label\":\"Email\",\"type\":\"email\",\"required\":true},{\"name\":\"message\",\"label\":\"Message\",\"type\":\"textarea\",\"required\":true}]}}]","seoJson":"{\"title\":\"Contact Us\"}"}]',
  'business,landing,professional,corporate',
  true, 1, 'system'
);

-- 3. Portfolio / Creative
INSERT INTO "WB_Templates" ("Name", "Description", "Category", "ThemeJson", "PagesJson", "Tags", "IsBuiltIn", "SortOrder", "CreatedBy")
VALUES (
  'Creative Portfolio',
  'Showcase your work with an elegant portfolio layout. Image gallery, about section, and contact.',
  'portfolio',
  '{"primaryColor":"#8b5cf6","secondaryColor":"#64748b","accentColor":"#f59e0b","backgroundColor":"#0f172a","textColor":"#f1f5f9","headingFont":"Space Grotesk, sans-serif","bodyFont":"Inter, sans-serif","borderRadius":12,"spacing":20,"shadowStyle":"dramatic","buttonStyle":"rounded","sectionPadding":1.2,"fontScale":1.1}',
  '[{"title":"Home","slug":"","isHomePage":true,"sortOrder":0,"componentsJson":"[{\"id\":\"hero-1\",\"type\":\"hero\",\"label\":\"Hero\",\"props\":{\"title\":\"Creative Designer\",\"subtitle\":\"Turning ideas into stunning digital experiences\",\"alignment\":\"left\",\"backgroundType\":\"gradient\"}},{\"id\":\"gallery-1\",\"type\":\"image-gallery\",\"label\":\"Portfolio Gallery\",\"props\":{\"title\":\"Selected Work\",\"columns\":3,\"items\":[]}},{\"id\":\"text-1\",\"type\":\"text\",\"label\":\"About\",\"props\":{\"content\":\"A brief introduction about your work and expertise.\"}}]","seoJson":"{\"title\":\"Creative Portfolio\"}"},{"title":"Contact","slug":"contact","isHomePage":false,"sortOrder":1,"componentsJson":"[{\"id\":\"form-1\",\"type\":\"form\",\"label\":\"Contact\",\"props\":{\"title\":\"Let''s Work Together\",\"fields\":[{\"name\":\"name\",\"label\":\"Name\",\"type\":\"text\",\"required\":true},{\"name\":\"email\",\"label\":\"Email\",\"type\":\"email\",\"required\":true},{\"name\":\"project\",\"label\":\"Project Details\",\"type\":\"textarea\",\"required\":true}]}}]","seoJson":"{\"title\":\"Contact\"}"}]',
  'portfolio,creative,gallery,dark',
  true, 2, 'system'
);

-- 4. Service Business (HVAC / Plumbing / Electrical)
INSERT INTO "WB_Templates" ("Name", "Description", "Category", "ThemeJson", "PagesJson", "Tags", "IsBuiltIn", "SortOrder", "CreatedBy")
VALUES (
  'Service Business',
  'Perfect for HVAC, plumbing, electrical, or any service-based business. Includes services list and booking CTA.',
  'business',
  '{"primaryColor":"#059669","secondaryColor":"#4b5563","accentColor":"#d97706","backgroundColor":"#ffffff","textColor":"#1e293b","headingFont":"Inter, sans-serif","bodyFont":"Inter, sans-serif","borderRadius":8,"spacing":16,"shadowStyle":"subtle","buttonStyle":"rounded","sectionPadding":1,"fontScale":1}',
  '[{"title":"Home","slug":"","isHomePage":true,"sortOrder":0,"componentsJson":"[{\"id\":\"hero-1\",\"type\":\"hero\",\"label\":\"Hero\",\"props\":{\"title\":\"Professional Service You Can Trust\",\"subtitle\":\"Licensed, insured, and ready to help. Available 24/7.\",\"ctaText\":\"Book Now\",\"ctaLink\":\"#contact\",\"alignment\":\"center\"}},{\"id\":\"features-1\",\"type\":\"features\",\"label\":\"Services\",\"props\":{\"title\":\"Our Services\",\"columns\":3,\"items\":[{\"icon\":\"Wrench\",\"title\":\"Repairs\",\"description\":\"Fast and reliable repair services\"},{\"icon\":\"Home\",\"title\":\"Installation\",\"description\":\"Professional installation by experts\"},{\"icon\":\"Clock\",\"title\":\"Maintenance\",\"description\":\"Preventive maintenance plans\"}]}},{\"id\":\"testimonials-1\",\"type\":\"testimonials\",\"label\":\"Reviews\",\"props\":{\"title\":\"What Our Customers Say\",\"items\":[{\"name\":\"John D.\",\"text\":\"Excellent service! They arrived on time and fixed the issue quickly.\",\"rating\":5}]}}]","seoJson":"{\"title\":\"Professional Services\"}"},{"title":"Services","slug":"services","isHomePage":false,"sortOrder":1,"componentsJson":"[{\"id\":\"hero-svc\",\"type\":\"hero\",\"label\":\"Services Hero\",\"props\":{\"title\":\"Our Services\",\"subtitle\":\"Complete solutions for your home and business\"}}]","seoJson":"{\"title\":\"Our Services\"}"},{"title":"Contact","slug":"contact","isHomePage":false,"sortOrder":2,"componentsJson":"[{\"id\":\"form-1\",\"type\":\"form\",\"label\":\"Contact Form\",\"props\":{\"title\":\"Request a Quote\",\"fields\":[{\"name\":\"name\",\"label\":\"Full Name\",\"type\":\"text\",\"required\":true},{\"name\":\"phone\",\"label\":\"Phone\",\"type\":\"text\",\"required\":true},{\"name\":\"service\",\"label\":\"Service Needed\",\"type\":\"text\",\"required\":true},{\"name\":\"message\",\"label\":\"Details\",\"type\":\"textarea\"}]}}]","seoJson":"{\"title\":\"Contact Us\"}"}]',
  'service,hvac,plumbing,electrical,contractor',
  true, 3, 'system'
);

-- 5. Restaurant / Food
INSERT INTO "WB_Templates" ("Name", "Description", "Category", "ThemeJson", "PagesJson", "Tags", "IsBuiltIn", "SortOrder", "CreatedBy")
VALUES (
  'Restaurant',
  'Appetizing restaurant template with menu, hours, location, and reservation form.',
  'restaurant',
  '{"primaryColor":"#dc2626","secondaryColor":"#78350f","accentColor":"#f59e0b","backgroundColor":"#fffbeb","textColor":"#1c1917","headingFont":"Playfair Display, serif","bodyFont":"Inter, sans-serif","borderRadius":4,"spacing":16,"shadowStyle":"subtle","buttonStyle":"rounded","sectionPadding":1,"fontScale":1}',
  '[{"title":"Home","slug":"","isHomePage":true,"sortOrder":0,"componentsJson":"[{\"id\":\"hero-1\",\"type\":\"hero\",\"label\":\"Hero\",\"props\":{\"title\":\"Authentic Italian Cuisine\",\"subtitle\":\"Fresh ingredients, traditional recipes, unforgettable flavors.\",\"ctaText\":\"View Menu\",\"ctaLink\":\"#menu\",\"alignment\":\"center\",\"backgroundType\":\"gradient\"}},{\"id\":\"text-menu\",\"type\":\"text\",\"label\":\"Menu Preview\",\"props\":{\"content\":\"## Our Specialties\\n\\nDiscover our chef-curated dishes made with the finest local ingredients.\"}},{\"id\":\"cta-1\",\"type\":\"cta-banner\",\"label\":\"Reservation CTA\",\"props\":{\"title\":\"Reserve Your Table\",\"subtitle\":\"Book online or call us at (555) 123-4567\",\"ctaText\":\"Make Reservation\",\"ctaLink\":\"#contact\"}}]","seoJson":"{\"title\":\"Italian Restaurant\",\"description\":\"Authentic Italian dining experience\"}"},{"title":"Menu","slug":"menu","isHomePage":false,"sortOrder":1,"componentsJson":"[{\"id\":\"hero-menu\",\"type\":\"hero\",\"label\":\"Menu Hero\",\"props\":{\"title\":\"Our Menu\",\"subtitle\":\"Seasonal selections prepared fresh daily\"}}]","seoJson":"{\"title\":\"Menu\"}"},{"title":"Contact","slug":"contact","isHomePage":false,"sortOrder":2,"componentsJson":"[{\"id\":\"form-1\",\"type\":\"form\",\"label\":\"Reservation\",\"props\":{\"title\":\"Make a Reservation\",\"fields\":[{\"name\":\"name\",\"label\":\"Name\",\"type\":\"text\",\"required\":true},{\"name\":\"phone\",\"label\":\"Phone\",\"type\":\"text\",\"required\":true},{\"name\":\"date\",\"label\":\"Date\",\"type\":\"text\",\"required\":true},{\"name\":\"guests\",\"label\":\"Number of Guests\",\"type\":\"text\",\"required\":true}]}}]","seoJson":"{\"title\":\"Reservations\"}"}]',
  'restaurant,food,menu,dining,cafe',
  true, 4, 'system'
);

-- 6. E-commerce / Product
INSERT INTO "WB_Templates" ("Name", "Description", "Category", "ThemeJson", "PagesJson", "Tags", "IsBuiltIn", "SortOrder", "CreatedBy")
VALUES (
  'Product Showcase',
  'Clean product showcase with features, pricing, and FAQ sections.',
  'ecommerce',
  '{"primaryColor":"#7c3aed","secondaryColor":"#6b7280","accentColor":"#06b6d4","backgroundColor":"#ffffff","textColor":"#1e293b","headingFont":"Inter, sans-serif","bodyFont":"Inter, sans-serif","borderRadius":12,"spacing":16,"shadowStyle":"subtle","buttonStyle":"rounded","sectionPadding":1,"fontScale":1}',
  '[{"title":"Home","slug":"","isHomePage":true,"sortOrder":0,"componentsJson":"[{\"id\":\"hero-1\",\"type\":\"hero\",\"label\":\"Product Hero\",\"props\":{\"title\":\"The Future of Productivity\",\"subtitle\":\"One tool to manage your entire workflow. Simple, powerful, and beautiful.\",\"ctaText\":\"Start Free Trial\",\"ctaLink\":\"#pricing\",\"alignment\":\"center\",\"backgroundType\":\"gradient\"}},{\"id\":\"features-1\",\"type\":\"features\",\"label\":\"Features\",\"props\":{\"title\":\"Everything You Need\",\"columns\":3,\"items\":[{\"icon\":\"Layers\",\"title\":\"Organized\",\"description\":\"Keep everything in one place\"},{\"icon\":\"Users\",\"title\":\"Collaborative\",\"description\":\"Work together seamlessly\"},{\"icon\":\"Smartphone\",\"title\":\"Mobile Ready\",\"description\":\"Access from anywhere\"}]}},{\"id\":\"pricing-1\",\"type\":\"pricing\",\"label\":\"Pricing\",\"props\":{\"title\":\"Simple Pricing\",\"plans\":[{\"name\":\"Starter\",\"price\":\"$9\",\"period\":\"mo\",\"features\":[\"5 Projects\",\"Basic Analytics\",\"Email Support\"]},{\"name\":\"Pro\",\"price\":\"$29\",\"period\":\"mo\",\"features\":[\"Unlimited Projects\",\"Advanced Analytics\",\"Priority Support\"],\"highlighted\":true},{\"name\":\"Enterprise\",\"price\":\"Custom\",\"period\":\"\",\"features\":[\"Custom Setup\",\"Dedicated Manager\",\"SLA\"]}]}},{\"id\":\"faq-1\",\"type\":\"faq\",\"label\":\"FAQ\",\"props\":{\"title\":\"Frequently Asked Questions\",\"items\":[{\"question\":\"How does the free trial work?\",\"answer\":\"You get 14 days of full access with no credit card required.\"},{\"question\":\"Can I cancel anytime?\",\"answer\":\"Yes, cancel anytime with no questions asked.\"}]}}]","seoJson":"{\"title\":\"Product - The Future of Productivity\"}"}]',
  'product,saas,pricing,ecommerce,launch',
  true, 5, 'system'
);

-- 7. Blog / Content
INSERT INTO "WB_Templates" ("Name", "Description", "Category", "ThemeJson", "PagesJson", "Tags", "IsBuiltIn", "SortOrder", "CreatedBy")
VALUES (
  'Blog & Content',
  'Minimal blog-style template for writers, creators, and content marketers.',
  'blog',
  '{"primaryColor":"#0f172a","secondaryColor":"#64748b","accentColor":"#3b82f6","backgroundColor":"#ffffff","textColor":"#334155","headingFont":"Georgia, serif","bodyFont":"Inter, sans-serif","borderRadius":4,"spacing":20,"shadowStyle":"none","buttonStyle":"rounded","sectionPadding":1.2,"fontScale":1.05}',
  '[{"title":"Home","slug":"","isHomePage":true,"sortOrder":0,"componentsJson":"[{\"id\":\"hero-1\",\"type\":\"hero\",\"label\":\"Blog Hero\",\"props\":{\"title\":\"Thoughts & Ideas\",\"subtitle\":\"A personal blog about technology, design, and creativity.\",\"alignment\":\"center\"}},{\"id\":\"text-1\",\"type\":\"text\",\"label\":\"Latest Post\",\"props\":{\"content\":\"## Welcome\\n\\nThis is where your latest blog posts and articles will appear. Start writing to share your ideas with the world.\"}},{\"id\":\"divider-1\",\"type\":\"divider\",\"label\":\"Divider\",\"props\":{}},{\"id\":\"text-2\",\"type\":\"text\",\"label\":\"Newsletter CTA\",\"props\":{\"content\":\"### Subscribe to the Newsletter\\n\\nGet the latest posts delivered straight to your inbox.\"}}]","seoJson":"{\"title\":\"Blog - Thoughts & Ideas\"}"},{"title":"About","slug":"about","isHomePage":false,"sortOrder":1,"componentsJson":"[{\"id\":\"text-about\",\"type\":\"text\",\"label\":\"About\",\"props\":{\"content\":\"## About Me\\n\\nShare your story, background, and what drives you to write.\"}}]","seoJson":"{\"title\":\"About\"}"}]',
  'blog,content,writing,minimal,personal',
  true, 6, 'system'
);

-- 8. Auto Repair / Garage
INSERT INTO "WB_Templates" ("Name", "Description", "Category", "ThemeJson", "PagesJson", "Tags", "IsBuiltIn", "SortOrder", "CreatedBy")
VALUES (
  'Auto Repair Shop',
  'Bold auto repair and car service template with service list, team section, and booking form.',
  'automotive',
  '{"primaryColor":"#dc2626","secondaryColor":"#1e293b","accentColor":"#f59e0b","backgroundColor":"#ffffff","textColor":"#0f172a","headingFont":"Space Grotesk, sans-serif","bodyFont":"Inter, sans-serif","borderRadius":8,"spacing":16,"shadowStyle":"subtle","buttonStyle":"rounded","sectionPadding":1,"fontScale":1}',
  '[{"title":"Home","slug":"","isHomePage":true,"sortOrder":0,"componentsJson":"[{\"id\":\"hero-1\",\"type\":\"hero\",\"label\":\"Hero\",\"props\":{\"title\":\"Expert Auto Repair\",\"subtitle\":\"Certified mechanics. Quality parts. Fair prices. We get you back on the road fast.\",\"ctaText\":\"Book Service\",\"ctaLink\":\"#contact\",\"alignment\":\"center\",\"backgroundType\":\"gradient\"}},{\"id\":\"features-1\",\"type\":\"features\",\"label\":\"Services\",\"props\":{\"title\":\"Our Services\",\"columns\":3,\"items\":[{\"icon\":\"Wrench\",\"title\":\"Engine Repair\",\"description\":\"Complete engine diagnostics and repair\"},{\"icon\":\"Car\",\"title\":\"Oil Change\",\"description\":\"Quick and affordable oil change service\"},{\"icon\":\"Shield\",\"title\":\"Brake Service\",\"description\":\"Brake inspection, repair and replacement\"}]}},{\"id\":\"testimonials-1\",\"type\":\"testimonials\",\"label\":\"Reviews\",\"props\":{\"title\":\"Customer Reviews\",\"items\":[{\"name\":\"Mike S.\",\"text\":\"Best mechanic in town. Honest pricing and great work.\",\"rating\":5},{\"name\":\"Sarah L.\",\"text\":\"They fixed my transmission issue same day. Highly recommend!\",\"rating\":5}]}}]","seoJson":"{\"title\":\"Auto Repair Shop\",\"description\":\"Expert auto repair and maintenance services\"}"},{"title":"Services","slug":"services","isHomePage":false,"sortOrder":1,"componentsJson":"[{\"id\":\"hero-svc\",\"type\":\"hero\",\"label\":\"Services\",\"props\":{\"title\":\"Full Service Auto Care\",\"subtitle\":\"From routine maintenance to major repairs\"}}]","seoJson":"{\"title\":\"Services\"}"},{"title":"Contact","slug":"contact","isHomePage":false,"sortOrder":2,"componentsJson":"[{\"id\":\"form-1\",\"type\":\"form\",\"label\":\"Booking Form\",\"props\":{\"title\":\"Schedule Service\",\"fields\":[{\"name\":\"name\",\"label\":\"Your Name\",\"type\":\"text\",\"required\":true},{\"name\":\"phone\",\"label\":\"Phone Number\",\"type\":\"text\",\"required\":true},{\"name\":\"vehicle\",\"label\":\"Vehicle (Year/Make/Model)\",\"type\":\"text\",\"required\":true},{\"name\":\"service\",\"label\":\"Service Needed\",\"type\":\"textarea\",\"required\":true}]}}]","seoJson":"{\"title\":\"Book Service\"}"}]',
  'automotive,garage,car,repair,mechanic',
  true, 7, 'system'
);

-- ══════════════════════════════════════════════════════════════
-- DONE — All 10 WB_ tables created + 7 brand profiles + 8 templates seeded
-- ══════════════════════════════════════════════════════════════
