using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using MyApi.Infrastructure;

namespace MyApi.Modules.ServiceOrders.Models
{
    [ModuleScope("service_orders")]
    [Table("ServiceOrders")]
    public class ServiceOrder : ITenantEntity, MyApi.Modules.Shared.Models.ISoftDeletable
    {
        public int TenantId { get; set; }

        public bool IsDeleted { get; set; } = false;
        public DateTime? DeletedAt { get; set; }
        public string? DeletedBy { get; set; }

        [Key]
        [Column("Id")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        [Column("OrderNumber")]
        [MaxLength(50)]
        public string OrderNumber { get; set; } = string.Empty;

        [Required]
        [Column("ContactId")]
        public int ContactId { get; set; }

        [Column("ProjectId")]
        public int? ProjectId { get; set; }

        [Column("OrderDate")]
        public DateTime OrderDate { get; set; } = DateTime.UtcNow;

        [Column("ServiceType")]
        [MaxLength(100)]
        public string ServiceType { get; set; } = string.Empty;

        [Required]
        [Column("Priority")]
        [MaxLength(20)]
        public string Priority { get; set; } = "medium";

        [Required]
        [Column("Status", TypeName = "text")]
        public string Status { get; set; } = "draft";

        [Column("ScheduledDate")]
        public DateTime? ScheduledDate { get; set; }

        [Column("CompletedDate")]
        public DateTime? CompletedDate { get; set; }

        [Column("TotalAmount", TypeName = "decimal(18,2)")]
        public decimal? TotalAmount { get; set; } = 0;

        [Column("Notes")]
        public string? Notes { get; set; }

        [Column("SaleId")]
        [MaxLength(50)]
        public string? SaleId { get; set; }

        [Column("OfferId")]
        [MaxLength(50)]
        public string? OfferId { get; set; }

        /// <summary>
        /// How this Service Order was created:
        ///   "from_sale"  — converted from a Sale (legacy / default path)
        ///   "from_offer" — converted directly from an Offer
        ///   "direct"     — created standalone, without Offer/Sale
        /// Drives the shadow-Sale flow in CompleteAsync.
        /// </summary>
        [Required]
        [Column("Origin")]
        [MaxLength(20)]
        public string Origin { get; set; } = "from_sale";

        /// <summary>
        /// When a "direct" order is completed, a shadow Sale is generated and
        /// its Id is stored here (and mirrored into SaleId so all downstream
        /// logic that reads SaleId keeps working unchanged). Null until then.
        /// </summary>
        [Column("AutoGeneratedSaleId")]
        public int? AutoGeneratedSaleId { get; set; }

        [Column("Description")]
        public string? Description { get; set; }

        [Column("StartDate")]
        public DateTime? StartDate { get; set; }

        [Column("TargetCompletionDate")]
        public DateTime? TargetCompletionDate { get; set; }

        [Column("ActualStartDate")]
        public DateTime? ActualStartDate { get; set; }

        [Column("ActualCompletionDate")]
        public DateTime? ActualCompletionDate { get; set; }

        [Column("EstimatedDuration")]
        public int? EstimatedDuration { get; set; }

        [Column("ActualDuration")]
        public int? ActualDuration { get; set; }

        [Column("EstimatedCost", TypeName = "decimal(18,2)")]
        public decimal? EstimatedCost { get; set; } = 0;

        [Column("ActualCost", TypeName = "decimal(18,2)")]
        public decimal? ActualCost { get; set; } = 0;

        [Column("Discount", TypeName = "decimal(18,2)")]
        public decimal? Discount { get; set; } = 0;

        [Column("DiscountPercentage", TypeName = "decimal(5,2)")]
        public decimal? DiscountPercentage { get; set; } = 0;

        [Column("Tax", TypeName = "decimal(18,2)")]
        public decimal? Tax { get; set; } = 0;

        [Column("PaymentStatus")]
        [MaxLength(20)]
        public string? PaymentStatus { get; set; } = "pending";

        [Column("PaymentTerms")]
        [MaxLength(20)]
        public string? PaymentTerms { get; set; } = "net30";

        [Column("InvoiceNumber")]
        [MaxLength(50)]
        public string? InvoiceNumber { get; set; }

        [Column("InvoiceDate")]
        public DateTime? InvoiceDate { get; set; }

        [Column("CompletionPercentage")]
        public int? CompletionPercentage { get; set; } = 0;

        [Column("RequiresApproval")]
        public bool RequiresApproval { get; set; } = false;

        [Column("ApprovedBy")]
        [MaxLength(50)]
        public string? ApprovedBy { get; set; }

        [Column("ApprovalDate")]
        public DateTime? ApprovalDate { get; set; }

        [Column("CancellationReason")]
        public string? CancellationReason { get; set; }

        [Column("CancellationNotes")]
        public string? CancellationNotes { get; set; }

        [Column("Tags")]
        public string[]? Tags { get; set; }

        [Column("PreferredSkills")]
        public string[]? PreferredSkills { get; set; }

        [Column("CustomFields", TypeName = "jsonb")]
        public string? CustomFields { get; set; }

        [Required]
        [Column("CreatedDate")]
        public DateTime CreatedDate { get; set; } = DateTime.UtcNow;

        [Required]
        [Column("CreatedBy")]
        [MaxLength(100)]
        public string CreatedBy { get; set; } = string.Empty;

        [Column("ModifiedDate")]
        public DateTime? ModifiedDate { get; set; }

        [Column("ModifiedBy")]
        [MaxLength(100)]
        public string? ModifiedBy { get; set; }

        // Contact geolocation (copied from contact for map display)
        [Column("ContactLatitude", TypeName = "decimal(10,7)")]
        public decimal? ContactLatitude { get; set; }

        [Column("ContactLongitude", TypeName = "decimal(10,7)")]
        public decimal? ContactLongitude { get; set; }

        [Column("ContactHasLocation")]
        public int ContactHasLocation { get; set; } = 0;

        // Helper columns for workflow/dispatch tracking
        [Column("TechnicallyCompletedAt")]
        public DateTime? TechnicallyCompletedAt { get; set; }

        [Column("ServiceCount")]
        public int ServiceCount { get; set; } = 0;

        [Column("CompletedDispatchCount")]
        public int CompletedDispatchCount { get; set; } = 0;

        // Navigation Properties
        public virtual ICollection<ServiceOrderJob>? Jobs { get; set; }
        public virtual ICollection<ServiceOrderMaterial>? Materials { get; set; }
    }
}
