using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using MyApi.Infrastructure;

namespace MyApi.Modules.Sales.Models
{
    [ModuleScope("sales")]
    [Table("SaleItems")]
    public class SaleItem : ITenantEntity
    {
        public int TenantId { get; set; }
        [Key]
        [Column("Id")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        [Column("SaleId")]
        public int SaleId { get; set; }

        [Column("ArticleId")]
        public int? ArticleId { get; set; }

        [Required]
        [Column("Description")]
        [MaxLength(500)]
        public string Description { get; set; } = string.Empty;

        [Required]
        [Column("Quantity", TypeName = "decimal(18,2)")]
        public decimal Quantity { get; set; } = 1;

        [Required]
        [Column("UnitPrice", TypeName = "decimal(18,2)")]
        public decimal UnitPrice { get; set; } = 0;

        [Column("Discount", TypeName = "decimal(5,2)")]
        public decimal? Discount { get; set; }

        [Required]
        [Column("TaxRate", TypeName = "decimal(5,2)")]
        public decimal TaxRate { get; set; } = 0;

        [Column("LineTotal", TypeName = "decimal(18,2)")]
        public decimal LineTotal { get; set; } = 0;

        [Column("DisplayOrder")]
        public int DisplayOrder { get; set; } = 0;

        [Column("Type")]
        [MaxLength(20)]
        public string Type { get; set; } = "article";

        [Column("ItemName")]
        [MaxLength(255)]
        public string? ItemName { get; set; }

        [Column("ItemCode")]
        [MaxLength(100)]
        public string? ItemCode { get; set; }

        [Column("InstallationId")]
        [MaxLength(50)]
        public string? InstallationId { get; set; }

        [Column("InstallationName")]
        [MaxLength(255)]
        public string? InstallationName { get; set; }

        [Column("DiscountType")]
        [MaxLength(20)]
        public string DiscountType { get; set; } = "percentage";

        [Column("RequiresServiceOrder")]
        public bool RequiresServiceOrder { get; set; } = false;

        [Column("ServiceOrderGenerated")]
        public bool ServiceOrderGenerated { get; set; } = false;

        [Column("ServiceOrderId")]
        [MaxLength(50)]
        public string? ServiceOrderId { get; set; }

        [Column("FulfillmentStatus")]
        [MaxLength(20)]
        public string? FulfillmentStatus { get; set; }

        // Currency this line was priced in. Populated from Sale.Currency at write
        // time so every historical line remembers its currency even if the parent
        // sale is later re-currencied. Nullable for legacy rows (interpreted as
        // the parent sale's Currency).
        [Column("Currency")]
        [MaxLength(10)]
        public string? Currency { get; set; }

        // Phase A (A2): FK lineage back to the OfferItem this SaleItem was
        // converted from. Explicit anchor so downstream code (planning copy,
        // materials rollup, invoicing) never has to rely on array-index pairing
        // between offer.Items and sale.Items. Nullable — direct-created sales
        // and deal→sale conversions leave it NULL.
        [Column("OriginOfferItemId")]
        public int? OriginOfferItemId { get; set; }

        // Source-row identity for lines generated by ServiceOrder invoice preparation.
        // Dispatch-sourced actuals (dispatch TimeEntries / Expenses / Materials) carry no
        // InvoiceStatus flag of their own, so before these columns existed the only
        // idempotency guard was a value signature over mutable fields (price / qty /
        // description). Any edit to the source row between two "Prepare for invoice" runs
        // produced a different signature and the same actual was billed twice.
        // SourceType/SourceId mirror the InvoiceLine.SourceType/SourceId convention and let
        // dedup key on stable row identity instead, so the user can re-plan and re-prepare
        // a service order as many times as they like without double-billing.
        // NULL for legacy rows and for manually authored sale lines.
        [Column("SourceType")]
        [MaxLength(40)]
        public string? SourceType { get; set; }

        [Column("SourceId")]
        [MaxLength(40)]
        public string? SourceId { get; set; }

        // Navigation Property
        [ForeignKey("SaleId")]
        public virtual Sale? Sale { get; set; }
    }
}
